version: '3.8'

services:
  web:
    build: .
    container_name: portal_interno_web
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TZ=America/Bogota
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/chatmc
      - SECRET_KEY=cambiar_esta_clave_en_produccion
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/static/uploads

  db:
    image: postgres:15-alpine
    container_name: portal_interno_db
    restart: always
    environment:
      - TZ=America/Bogota
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=chatmc
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
