"""Add TimeTracking tables

Revision ID: 22854e0785af
Revises: 63a1b47eda71
Create Date: 2026-01-29 12:13:51.395669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22854e0785af'
down_revision = '63a1b47eda71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_status')

    # ### end Alembic commands ###
