"""Initial Migration

Revision ID: 63a1b47eda71
Revises: 
Create Date: 2026-01-29 11:41:19.641778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a1b47eda71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('eps', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('arl', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('caja_compensacion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fondo_pensiones', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cesantias', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('entidad_bancaria', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero_cuenta', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tipo_sangre', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tipo_sangre')
        batch_op.drop_column('direccion')
        batch_op.drop_column('numero_cuenta')
        batch_op.drop_column('entidad_bancaria')
        batch_op.drop_column('cesantias')
        batch_op.drop_column('fondo_pensiones')
        batch_op.drop_column('caja_compensacion')
        batch_op.drop_column('arl')
        batch_op.drop_column('eps')
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
