"""Migracion inicial a PostgreSQL

Revision ID: 6642fce1ecca
Revises: 
Create Date: 2026-04-09 16:33:17.357754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6642fce1ecca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_pause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url_video', sa.String(length=255), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('esta_activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('eps', sa.String(length=100), nullable=True),
    sa.Column('arl', sa.String(length=100), nullable=True),
    sa.Column('caja_compensacion', sa.String(length=100), nullable=True),
    sa.Column('fondo_pensiones', sa.String(length=100), nullable=True),
    sa.Column('cesantias', sa.String(length=100), nullable=True),
    sa.Column('entidad_bancaria', sa.String(length=100), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('tipo_sangre', sa.String(length=10), nullable=True),
    sa.Column('current_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_event_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_event_start'), ['start'], unique=False)

    op.create_table('comunicado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incapacidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('dias_totales', sa.Integer(), nullable=False),
    sa.Column('diagnostico', sa.String(length=255), nullable=True),
    sa.Column('entidad_salud', sa.String(length=100), nullable=True),
    sa.Column('archivo_soporte', sa.String(length=255), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('comentarios_admin', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_permiso', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pause_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pause_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('programado_para', sa.DateTime(), nullable=True),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pause_id'], ['active_pause.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_advance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_revision', sa.DateTime(), nullable=True),
    sa.Column('revisado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['revisado_por'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(length=20), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('salario_base', sa.Float(), nullable=True),
    sa.Column('auxilio_transporte', sa.Float(), nullable=True),
    sa.Column('bonificaciones', sa.Float(), nullable=True),
    sa.Column('dias_injustificados', sa.Integer(), nullable=True),
    sa.Column('valor_descuento_dias', sa.Float(), nullable=True),
    sa.Column('aporte_salud', sa.Float(), nullable=True),
    sa.Column('aporte_pension', sa.Float(), nullable=True),
    sa.Column('otros_descuentos', sa.Float(), nullable=True),
    sa.Column('neto_pagar', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('texto_pregunta', sa.String(length=500), nullable=False),
    sa.Column('tipo_respuesta', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('respondido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('new_status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('es_dia_laboral', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dia_semana', name='uq_user_dia_semana')
    )
    op.create_table('event_attendees',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    op.create_table('group_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)

    op.create_table('survey_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('respuesta_texto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['survey_question.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['survey_response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('texto_opcion', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_option')
    op.drop_table('survey_answer')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))

    op.drop_table('message')
    op.drop_table('group_members')
    op.drop_table('event_attendees')
    op.drop_table('weekly_schedule')
    op.drop_table('training')
    op.drop_table('time_log')
    op.drop_table('survey_response')
    op.drop_table('survey_question')
    op.drop_table('payroll_doc')
    op.drop_table('payroll_advance')
    op.drop_table('pause_assignment')
    op.drop_table('leave_request')
    op.drop_table('incapacidad')
    op.drop_table('group')
    op.drop_table('comunicado')
    with op.batch_alter_table('calendar_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_event_start'))
        batch_op.drop_index(batch_op.f('ix_calendar_event_end'))

    op.drop_table('calendar_event')
    op.drop_table('user')
    op.drop_table('survey')
    op.drop_table('active_pause')
    # ### end Alembic commands ###
