"""Split descuentos_ley into aporte_salud and aporte_pension

Revision ID: 849820c13154
Revises: ebfae7dda54b
Create Date: 2026-01-29 12:43:12.451846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849820c13154'
down_revision = 'ebfae7dda54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_doc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aporte_salud', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('aporte_pension', sa.Float(), nullable=True))
        batch_op.drop_column('descuentos_ley')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_doc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuentos_ley', sa.FLOAT(), nullable=True))
        batch_op.drop_column('aporte_pension')
        batch_op.drop_column('aporte_salud')

    # ### end Alembic commands ###
