"""Add Group Chat

Revision ID: b55beee373ad
Revises: 55f577703651
Create Date: 2026-01-29 15:13:55.459544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55beee373ad'
down_revision = '55f577703651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('group',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('created_by', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=True),
    # sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('group_members',
    # sa.Column('user_id', sa.Integer(), nullable=False),
    # sa.Column('group_id', sa.Integer(), nullable=False),
    # sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    # sa.PrimaryKeyConstraint('user_id', 'group_id')
    # )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_message_group_id', 'group', ['group_id'], ['id'])

    # with op.batch_alter_table('payroll_doc', schema=None) as batch_op:
    #     batch_op.alter_column('periodo',
    #            existing_type=sa.VARCHAR(length=20),
    #            nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('payroll_doc', schema=None) as batch_op:
    #     batch_op.alter_column('periodo',
    #            existing_type=sa.VARCHAR(length=20),
    #            nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint('fk_message_group_id', type_='foreignkey')

        batch_op.drop_column('group_id')

    op.drop_table('group_members')
    op.drop_table('group')
    # ### end Alembic commands ###
