"""Add periodo column to PayrollDoc

Revision ID: c2c0d30790c9
Revises: 849820c13154
Create Date: 2026-01-29 12:53:29.920522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c0d30790c9'
down_revision = '849820c13154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_doc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_doc', schema=None) as batch_op:
        batch_op.drop_column('periodo')

    # ### end Alembic commands ###
