"""Add financial fields to PayrollDoc

Revision ID: ebfae7dda54b
Revises: 22854e0785af
Create Date: 2026-01-29 12:38:13.012337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfae7dda54b'
down_revision = '22854e0785af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_doc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salario_base', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('auxilio_transporte', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bonificaciones', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dias_injustificados', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_descuento_dias', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('descuentos_ley', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('otros_descuentos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('neto_pagar', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payroll_doc', schema=None) as batch_op:
        batch_op.drop_column('neto_pagar')
        batch_op.drop_column('otros_descuentos')
        batch_op.drop_column('descuentos_ley')
        batch_op.drop_column('valor_descuento_dias')
        batch_op.drop_column('dias_injustificados')
        batch_op.drop_column('bonificaciones')
        batch_op.drop_column('auxilio_transporte')
        batch_op.drop_column('salario_base')

    # ### end Alembic commands ###
